version: 1.0.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
clone_depth: 5
dotnet_csproj:
  patch: true
  file: src\**\*.csproj
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: dotnet restore
- cmd: if not exist ".\artifacts" mkdir ".\artifacts"
build:
  verbosity: minimal
artifacts:
- path: ./artifacts/*
  name: Microsoft.EntityFrameworkCore.Testing.FakeItEasy
after_build:
- ps: '& { dotnet pack .\src\Microsoft.EntityFrameworkCore.Testing.FakeItEasy\Microsoft.EntityFrameworkCore.Testing.FakeItEasy.csproj -c Release --no-restore --no-build -o ..\..\artifacts --version-suffix=$env:APPVEYOR_BUILD_NUMBER /p:Platform="" }'
- cmd: cd .\artifacts
- cmd: dir
- cmd: cd ..
on_failure:
- ps: $root = (Resolve-Path artifacts); [IO.Directory]::GetFiles($root.Path, '*.*', 'AllDirectories') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName failed-build }
